import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '../lib/utils'
import Navbar from '@/components/navbar'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/providers'
import "react-loading-skeleton/dist/skeleton.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <Providers>
      <html lang="en" className='light'>
        <body className={cn(inter.className, 'min-h-screen font-sans antialiased grainy ')}>
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>

  )
}
